### PR TITLE
Handler update

### PR DESCRIPTION
**Pull request by sekyondaMeta**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Updates to the following:
1. Added FAQs and Performance guide to contents menu,
2. Updated performance guide with more information per issue #2334 (This is a work in progress so more updates to come).
3. Hoping this push will force update the ts.torch_handler package page to fix issue #2048
Fixes #(issue)
4. Added benchmark and jmeter html files (plus supporting files) as well to fix broken links

## Type of change

Please delete options that are not relevant.

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Built site locally on machine and all three updates above seem to work, see screenshot:
Screenshot 2023-06-06 at 6 05 06 PM

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Review by lxning — COMMENTED** [review]
- benchmark.md is a duplication of https://github.com/pytorch/serve/blob/master/benchmarks/README.md. 
- jmeter.md is a duplication of https://github.com/pytorch/serve/blob/master/benchmarks/jmeter.md

Code/doc duplication makes maintenance difficult.

**Comment by msaroufim** [comment]
I'd be OK if we moved most of the docs we have that are outside of `docs/` to `docs/` if we link to them. That way we don't have to maintain 2 separate docs and get the benefit of a nicely rendered web page

**Comment by sekyondaMeta** [comment]
> * benchmark.md is a duplication of https://github.com/pytorch/serve/blob/master/benchmarks/README.md.
> * jmeter.md is a duplication of https://github.com/pytorch/serve/blob/master/benchmarks/jmeter.md
> 
> Code/doc duplication makes maintenance difficult.

I definitely agree duplication makes it tough to make changes. This was a quick update for now to fix some broken links and not necessarily the direction I want to go.

That said, the hope is to eventually get to a point where most (if not all) the links on the website lead to html pages of the source. The problem with that right now is that a lot of the sources are in different folders and so do not get built as part of the site and I have been thinking of the best way to set it up so that the sources get built as well.

@msaroufim I have considered moving docs to one folder and it could be the way to go. The tutorials repo does something like this and I like the idea of docs existing in one place. 
Problem is right now there are a lot of links out there not just on our site that reference the original github docs. 
Another idea is am considering/looking into is to make all .mds and place them in the html folder.

**Comment by msaroufim** [comment]
Hi @sekyondaMeta what happened to this PR? It might make sense to still keep and merge the changes to the performance guide and we can worry about consolidating all docs in one folder later

**Comment by sekyondaMeta** [comment]
> Hi @sekyondaMeta what happened to this PR? It might make sense to still keep and merge the changes to the performance guide and we can worry about consolidating all docs in one folder later

I added the performance updates I had made in this one to the Landing Page PR so those should be live as well. 
I did set the benchmark files back to the original and fixed the links to point to the GitHub page instead of the html page which was where the duplication was coming from.

**Pull request closed without merging**
