### PR TITLE
Added cu125 image to support Ubuntu 24.04

### LINKED ISSUE #3278: Support for a CUDA 12.5.x
### 🚀 The feature

I pushed the container and saw over 500 CVEs when I scanned the container. Many, if not all, would be addressed if we support Ubuntu 24.04. NVIDA has a docker image running 24.04 as it's base and it runs 12.5.1. I would like to update the build scripts to support this imae

### Motivation, pitch

500+ CVEs related to the base image using 20.04

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jasonsmithio**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

I pushed the existing container and saw over 500 CVEs when I scanned the container. Many, if not all, would be addressed if we support Ubuntu 24.04. NVIDA has a docker image running 24.04 as it's base and it runs 12.5.1. I went ahead and added build support for it. As far as I can tell, nothing is broken in this version. 

Fixes #3278

## Type of change

- [ x] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update (maybe)

## Feature/Issue validation/testing

No formal unit test. I built the container without error. This one has only 116 vulnerabilities vs 596 in previous version. 2 CVEs are high and he remaining are Medium (97) and Low (17). 

Used the container and didn't notice any issues differing from the previous version.  I am open to doing more tests if need be. 

## Checklist:

- [x ] Did you have fun?
- [x ] Have you added tests that prove your fix is effective or that this feature works?

### CODE REVIEW

**Comment by mreso** [comment]
@ankithagunapal do you recall what kind of issues you were facing when updating to 24.04? Otherwise it would be great to move forward with this.

**Comment by agunapal** [comment]
@mreso CI / regressions with ubuntu 22 were flaky. Hence we didn't upgrade. Haven't tried that in a while.

**Comment by jasonsmithio** [comment]
What exactly were the regression issues? I tested and didn't notice anything out of the ordinary when I deployed this on Ubuntu 24.04

**Comment by agunapal** [comment]
> What exactly were the regression issues? I tested and didn't notice anything out of the ordinary when I deployed this on Ubuntu 24.04

@jasonsmithio The workflows you see in this file, you can try updating them to ubuntu 22 or 24 (atleast the CPU ones) . For CUDA versions, we follow PyTorch, So first step would be to support 12.4 , Python version too, we could try updating to 3.10 first

**Pull request closed without merging**
