### PR TITLE
Upgrade to ubuntu22.04 to fix security issues.

### PR DESCRIPTION
**Pull request by jack-gits**
There're still many security issues on ubuntu20.04, in order to improve the security, need upgrade to ubuntu 22.04.

ubuntu22.04 is only available for cu117 as nvidia/cuda only provide ubuntu22.04 for cu117 or above.

below is an example of security issues.

image

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] regression testing

image

image

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by msaroufim** [comment]
We encountered a lot of flakiness on our ubuntu CI when we moved from 18.04 to 22.04 or 20.04. This is an issue because I'd rather we use the same Ubuntu version everywhere so both for the docker files and anything under `.github/workflows` otherwise there's always a chance that a small dependency change breaks everything.

Also I'm still not sure what our policy should be for medium or low impact security issues, my worry is we'd spend too much time upgrading dependencies as opposed to focusing on the bigger security issues

**Comment by jack-gits** [comment]
we have very strict security policy, medium issues should be fixed as far as possible.

**Comment by msaroufim** [comment]
Hi @jack-gits do you mind emailing me? It's my firstnamelastname@meta.com - since security is obviously important to you, I'd rather we discuss things in more depth there

**Comment by jack-gits** [comment]
> 

have you got my email by jackxu081@gmail.com?

**Comment by msaroufim** [comment]
I believe I missed your original, email just emailed you now

**Pull request closed without merging**
