### PR TITLE
Prometheus Plugin

### LINKED ISSUE #611: Enhance ServingSDK to support mertic endpoint and convert prometheus metric collector as plugin
## Is your feature request related to a problem? Please describe.

 - The current metric API implementation creates a dependency on [Prometheus packages](https://github.com/pytorch/serve/blob/master/frontend/gradle.properties#L5)

 - TorchServe should allow users to add different metrics collection frameworks similar to Prometheus.
 
 - Prometheus metric collector should be available as a plugin and not as an inbuilt framework.

## Describe the solution

 - Enhance ServingSDK to support mertic endpoint

 - Convert prometheus metric collector as plugin

### PR DESCRIPTION
**Pull request by maheshambule**
## Description

This PR adds support for the Prometheus Metric Endpoint plugin.
With this PR all the Metrics which get logged to Metric loggers are exposed to plugins. It includes System Metrics,
Request count metrics, Time Latency metrics, and any custom metric which is added by the user. The plugin can be extended or a new plugin can be added based on this plugin.

1. Plugin endpoint
2. Support in SDK for pluggable logging event listener 
3. Profiling PR is merged into this PR - https://github.com/pytorch/serve/pull/666
4. Documentation - metrics.md, metric_api.md, metrics_plugin.md
5. Test cases in Frontend, SDK and Plugin

Fixes #611 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X] This change requires a documentation update

## Feature/Issue validation/testing

- UT/IT execution results

- Logs

## Checklist:

- [ X] Have you added tests that prove your fix is effective or that this feature works?
- [ X] New and existing unit tests pass locally with these changes?
- [ X] Has code been commented, particularly in hard-to-understand areas?
- [ X] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by maheshambule** [comment]
@maaquib, @dhanainme Please take a look. 
CodeBuild is failing as SDK in Maven repo is not updated with the new changes.

**Comment by maaquib** [comment]
Blocker by #728

**Comment by HamidShojanazeri** [comment]
@maheshambule I tried to install from source on branch issue_611, however, it fails to build, here is error log, 
[PR_722.log](https://github.com/pytorch/serve/files/5418529/PR_722.log).

**Comment by maheshambule** [comment]
@HamidShojanazeri, It is failing because this PR  adds changes in the SDK as well. The SDK jar with these changes is not added to the Maven Repo yet. I will be working with @maaquib, @dhanainme to get it added to Repo. In the meantime, if you want to use the branch please build an SDK jar first and add it to your local maven repo.

**Comment by maaquib** [comment]
@maheshambule Can you separate out the plugins changes into a separate PR. That way it would be easier to review and integrate.

**Comment by maheshambule** [comment]
@maaquib, Do you want me to separate out Profiling part from the Plugin? That way we will have 2 PRs.

There is also another way where I will create small 4 PRs for each component - SDK, TorchServe Metric Plugin Changes, Prometheus Plugin, and Profiling changes. Once SDK changes are reviewed, we can create a Jar and publish it to the Maven.

**Comment by maheshambule** [comment]
@maaquib, I have created a separate PR for SDK changes. https://github.com/pytorch/serve/pull/763
Could you please review it? Once it is merged I will update this PR.

**Comment by maaquib** [comment]
@maheshambule Can you resolve the conflicts here

**Comment by chauhang** [comment]
@maheshambule Please resolve the conflicts for the PR

**Comment by lxning** [comment]
@maheshambule could you pls fix the build errors and conflicts?

**Comment by maheshambule** [comment]
@maaquib, @chauhang, @lxning, I have resolved conflicts.
The build is failing because it needs SDK version 0.0.4 which has SDK changes for Metric Plugin support.
Request you to publish the latest SDK changes to the Maven repo.

**Comment by maaquib** [comment]
Pending regression tests after mvn release of new sdk

**Comment by chauhang** [comment]
@maheshambule Please resolved the merge conflicts on this PR.

**Comment by maheshambule** [comment]
will look into build failures

**Comment by msaroufim** [comment]
Closing as Prometheus is supported in master. Usage instructions and proof here #1113

**Comment by donchesworth** [comment]
@msaroufim @lxning @maaquib  I think there's some confusion here. The [Metrics API](https://pytorch.org/serve/metrics_api.html) has been available and working since v0.2.0. At that time, inference latency, queue latency, and inference requests were all available. This PR upgrade is/was to add an additional [13 system metrics](https://pytorch.org/serve/metrics.html#system-metrics), currently collected in `ts_metrics.log` that are not accessible at the 8082/metrics endpoint.

It looks like the proof in #1113 that we don't need an upgrade is that the original works. 😄  Please consider reopening this PR. Thanks so much!

**Comment by msaroufim** [comment]
This work is now being tracked in #1492

**Pull request closed without merging**
