### PR TITLE
Ad Security.md to TorchServe site

### PR DESCRIPTION
**Pull request by sekyondaMeta**
Adding Security.md doc to TorchServe site

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Feature/Issue validation/testing

Previewed pages locally on my machine

Screenshot 2023-11-10 at 4 43 26 PM

Screenshot 2023-11-10 at 4 43 13 PM

## Checklist:

- [x] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by sekyondaMeta** [comment]
@ankithagunapal Take a look and let me know. 
symlink was giving me a lot of trouble (long story), but I found a not so pretty way to include the SECURITY.md file while still leaving it where it is. 
The makefile creates a copy of it in the docs folder each time it builds the docs, so any changes to the original should eventually propagate through to the html page.

**Review by agunapal — COMMENTED** [review]
Thanks @sekyondaMeta . Just to be clear, do we need to copy the file and send a new PR every time the security.md is updated?

**Comment by agunapal** [comment]
> @ankithagunapal Take a look and let me know. symlink was giving me a lot of trouble (long story), but I found a not so pretty way to include the SECURITY.md file while still leaving it where it is. The makefile creates a copy of it in the docs folder each time it builds the docs, so any changes to the original should eventually propagate through to the html page.

Just saw your comment. This is great. Thanks!

**Review by agunapal — APPROVED** [review]
LGTM

**Pull request merged**
