### PR TITLE
Torchserve Metrics support for Intel GPUs enabled

### PR DESCRIPTION
**Pull request by krish-navulla**
## Description
This PR is dependent on successful merge of #3132 

This pull request (PR) leverages `xpu-smi `to acquire Intel GPU metrics. For this functionality to operate correctly, #3132 must be merged, and in the config.properties file, `ipex_gpu_enable=true` must be configured.

To conduct testing on this PR, you can fetch the code from #3132 , compile the frontend jar, and update the Python environment files with the files from the fetched code.

Please review this pull request. @min-jean-cho , can you please take a look?

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Review by agunapal — CHANGES_REQUESTED** [review]
Please move the file `intel_gpu_metric_collector.py` to the example folder in the other PR.

**Review by agunapal — APPROVED** [review]
LGTM

**Comment by agunapal** [comment]
Hi @Kanya-Mo Could you please fix the lint issue here as well

**Comment by Kanya-Mo** [comment]
Sure. Done fixing.

**Comment by Kanya-Mo** [comment]
Sorry just fix the rest of files. Could you please start the workflows again?

**Pull request merged**
