### PR TITLE
Modifies the expected result and s3 location for the new text classifier model zoo

### PR DESCRIPTION
**Pull request by abishekchiffon**
## Description
Modifies the expected result and s3 location in the inference_data of the postman tests for the new text classifier model zoo at https://torchserve.pytorch.org/mar_files/my_text_classifier_v3.mar.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Regression test logs:
[ec2_gpu_regression_tests_all.log](https://github.com/pytorch/serve/files/5697410/ec2_gpu_regression_tests_all.log)

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by maaquib** [comment]
@abishekchiffon Still seeing failure in regression tests. Please fix this

```
# g4dn.xl, DLAMI 38
git clone https://github.com/abishekchiffon/serve
cd serve
git checkout tc_regression
python ts_scripts/install_dependencies.py --environment=dev
python test/regression_tests.py
```

```

┌─────────────────────────┬─────────────────────┬────────────────────┐
│                         │            executed │             failed │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              iterations │                  22 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│                requests │                  88 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│            test-scripts │                  88 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│      prerequest-scripts │                   0 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              assertions │                 105 │                  5 │
├─────────────────────────┴─────────────────────┴────────────────────┤
│ total run duration: 4m 7.4s                                        │
├────────────────────────────────────────────────────────────────────┤
│ total data received: 4.83MB (approx)                               │
├────────────────────────────────────────────────────────────────────┤
│ average response time: 2.7s [min: 3ms, max: 22.3s, s.d.: 5.6s]     │
├────────────────────────────────────────────────────────────────────┤
│ average DNS lookup time: 354µs [min: 120µs, max: 1ms, s.d.: 364µs] │
├────────────────────────────────────────────────────────────────────┤
│ average first byte time: 2.7s [min: 1ms, max: 22.3s, s.d.: 5.6s]   │
└────────────────────────────────────────────────────────────────────┘

  #  failure                          detail

 1.  AssertionError                   Successful POST request
     iteration: 1                     expected 400 to be one of [ 200 ]
                                      at assertion:0 in test-script
                                      inside "Model Zoo - Register Model"

 2.  AssertionError                   Successful POST request
     iteration: 1                     expected 404 to be one of [ 200 ]
                                      at assertion:0 in test-script
                                      inside "Model Zoo - Inference Model"

 3.  AssertionError                   Test expected JSON response
     iteration: 1                     expected false to be true
                                      at assertion:1 in test-script
                                      inside "Model Zoo - Inference Model"

 4.  AssertionError                   Successful DELETE request
     iteration: 1                     expected 404 to be one of [ 200, 201, 202 ]
                                      at assertion:0 in test-script
                                      inside "Model Zoo - Unregister model"

 5.  AssertionError                   Successful GET request
     iteration: 1                     expected '# HELP ts_inference_latency_microseconds Cumulative inference duration in microseconds\n# TYPE
                                      ts_inference_latency_microseconds counter\n# HELP ts_inference_requests_total Total number of inference requests.\n# TYPE
                                      ts_inference_requests_total
                                      counter\nts_inference_requests_total{uuid="d0321bb9-a59e-42f3-bb85-e713cde65a98",model_name="my_text_classifier",model_version=…
                                      1.0\n# HELP ts_queue_latency_microseconds Cumulative queue duration in microseconds\n# TYPE ts_queue_latency_microseconds
                                      counter\n' to match /ts_inference_latency_microseconds{uuid="[\w]{8}(-[\w]{4}){3}-[\w]{12}",model_name="my_text_classifier/
                                      at assertion:0 in test-script
                                      inside "Model Zoo - Model Metrics"
```

**Comment by lokeshgupta1975** [comment]
Review and merge please?

**Comment by maaquib** [comment]
> Review and merge please?

@lokeshgupta1975 The regression test is still failing as mentioned above. this needs to be fixed

**Comment by jeremiahschung** [comment]
It seems like the file `my_text_classifier_v3.mar` is not yet up on the S3 torchserve bucket: 
https://torchserve.s3.amazonaws.com/mar_files/my_text_classifier_v3.mar (fail to retrieve)
https://torchserve.s3.amazonaws.com/mar_files/my_text_classifier_v2.mar (successfully downloaded)

Once the mar file is available on the existing S3 bucket, the URL `torchserve.pytorch.org/mar_files/filename.mar` should work since `torchserve.pytorch.org` is just an alias for `torchserve.s3.amazonaws.com`.

**Comment by maaquib** [comment]
> It seems like the file `my_text_classifier_v3.mar` is not yet up on the S3 torchserve bucket:
> https://torchserve.s3.amazonaws.com/mar_files/my_text_classifier_v3.mar (fail to retrieve)
> https://torchserve.s3.amazonaws.com/mar_files/my_text_classifier_v2.mar (successfully downloaded)
> 
> Once the mar file is available on the existing S3 bucket, the URL `torchserve.pytorch.org/mar_files/filename.mar` should work since `torchserve.pytorch.org` is just an alias for `torchserve.s3.amazonaws.com`.

@jeremiahschung My bad. Looks like once I upload a new version the file loses its public access. Will test again

**Review by chauhang — APPROVED** [review]

**Review by maaquib — APPROVED** [review]
Made the mar files publis in s3. Works. Thanks @abishekchiffon

**Pull request merged**
