### PR TITLE
check number of available bytes before read

### PR DESCRIPTION
**Pull request by fefe982**
## Description

The frontend communicates with the backend using unix socket or tcp. During the transmission of TCP, the data might be split at any byte in between, and must be reconstructed at the receiver end to form a full bulk of data. And int of 4 bytes with the value of 0x12345678 sent by the sender might be split into two packets, with one ending with 0x5678, the next starting with 0x1234 (depending on the byte order used to transmit the int). So there must be a check for completeness of the data, before interpreting it as an int. 

This check exists for every read in `ModelResponseDecoder.decode`, except for the `httpStausCode`. This is possible cause for #734 . This fix incorprate the fix mentioned by @punshriv at in [this comment](https://github.com/pytorch/serve/issues/734#issuecomment-745279709)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by msaroufim** [comment]
Hi @fefe982 interesting catch. Can you confirm that issue #734 indeed goes away once this is done. Also looks like the CI is failing.

Thank you for the investigative work!

**Comment by fefe982** [comment]
#734 is kind of random and kind of highly rely on network stack of the OS. It is hard to reproduce so hard to confirm that it is "gone".

I cannot personally confirm the effect of the fix on #734. One of my colleagues, who has already left our company, met this problem. This problem can be confirmed with several of my other colleagues.  He left this fixed code, which he claims that it fixed the problem. As a matter of fact, with this fix, our service online is not suffering from this problem anymore.

This should fix #734 theoretically.

For the failing CI, I would need some help. I don't know what happened based on the log.

**Comment by fefe982** [comment]
I'm have the problem described in #734 in one of my projects now. And I can confirm that this fixes the problem for me.

**Comment by punshriv** [comment]
@fefe982 i am one of the original reporters of #734 and i can confirm that this issue gets resolved by the suggested fix so it will be great if we have this merged.

**Review by lxning — APPROVED** [review]

**Review by maaquib — APPROVED** [review]

**Pull request merged**
