### PR TITLE
[WIP] added bert seq classification torchscript model

### LINKED ISSUE #596: Add bert scripted models in sanity script
Now that we have HF Bert scripted models working on all GPUs instances we should revert the changes in https://github.com/pytorch/serve/pull/565

https://torchserve.s3.amazonaws.com/mar_files/BERTSeqClassification_Torchscript_gpu.mar

### PR DESCRIPTION
**Pull request by harshbafna**
## Description
 - added bert seq classification torchscript model

Fixes #596 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Feature/Issue validation/testing

- Logs

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?

### CODE REVIEW

**Comment by maaquib** [comment]
@harshbafna Ping for conflict resolution

**Comment by harshbafna** [comment]
@maaquib: There is a problem with transformers module and we need to build different mar files for CPU and GPU for BERT models and hence it is not feasible to add these models in our sanity script as of now. These have been removed from the regression suite as well.

Can we move this out to 0.4.0 release?

**Comment by maaquib** [comment]
Moved to 0.4.0 release

**Comment by msaroufim** [comment]
BERT sequence classification is supported https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers

**Pull request closed without merging**
