### PR TITLE
Add InvalidArgumentException

### PR DESCRIPTION
**Pull request by valboldakov**
## Description

Closes https://github.com/pytorch/serve/issues/1142

This  PR intends to implement the enhancement from https://github.com/pytorch/serve/issues/1142

Use-case in a client code:

```
from ts.service import InvalidArgumentException
...
    val: int = int(data[0].get( "val"))
    if val < min_val or val > max_val:
        raise InvalidArgumentException(f"Requested val {val} is too big or too small.")
```

### CODE REVIEW

**Comment by valboldakov** [comment]
@msaroufim @saurabheights-ecr

Would you please review it and tell me what do I need to enhance or fix?

**Comment by msaroufim** [comment]
Looks good to me, the main thing I'd caution though is that for batch inference this may not be the desired behavior. You'd rather gracefully ignore an example rather than throw an exception but in this case since we're not forcing anyone to throw an exception unless they want to in a handler then this looks good

**Comment by msaroufim** [comment]
Looks good to me, the main thing I'd caution though is that for batch inference this may not be the desired behavior. You'd rather gracefully ignore an example rather than throw an exception but in this case since we're not forcing anyone to throw an exception unless they want to in a handler then this looks good

**Comment by lxning** [comment]
handler can throw different exception depending on different scenarios. This PR is not a generic solution, not able to cover different use cases. I filed a [ticket](https://github.com/pytorch/serve/issues/1309) to cover all use cases. So I'm going to close this PR.

**Comment by valboldakov** [comment]
@lxning 

Thank you for your review!

Maybe I could change `InvalidArgumpythonentException` to `PredictionException` and provide error code to the interface?

So user's use-case will be:

```python
from ts.service import PredictionException

val: int = int(data[0].get( "val"))
if val < min_val or val > max_val:
    raise PredictionException(f"Requested val {val} is too big or too small.", 400)
```

And in the service code we'll:

```python
except PredictionException as argument_exception:
            logger.warning("Invoking custom service failed, invalid arguments.", exc_info=True)
            return create_predict_response(None, req_id_map, str(argument_exception), argument_exception.error_code))
```

What do you think?

cc @msaroufim @HamidShojanazeri

**Comment by lxning** [comment]
@valboldakov Thank you for the reply.

The exception should be thrown from model's handler. Here is an [example](https://github.com/dhanainme/multi-model-server/blob/cd5a693032b1bec4c46b0f7a9844df496a62c1a8/frontend/modelarchive/src/test/resources/models/custom-return-code/service.py#L17). In other words, PredictionException message should be able to allow customization. I'll land the [code](https://github.com/awslabs/multi-model-server/pull/965/files) into TS.

Thanks again!

**Pull request closed without merging**
