### PR TITLE
Added `pre-commit`

### LINKED ISSUE #1598: Adding `pre-commit`
## Is your feature request related to a problem? Please describe.

To ensure the quality of commits, have a stage to be run before any commit.

## Describe the solution
Utilizing [`pre-commit`](https://pre-commit.com/), which is a Git hook that is triggered on every commit to automatically detect issues in code. 

I have used `pre-commit` and there are multiple hooks that can be added, such as:
- [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) - set of useful hooks. For more hooks, check [this](https://github.com/pre-commit/pre-commit-hooks#hooks-available)
	- `check-ast` - Simply check whether files parse as valid python.
	- `check-builtin-literals` - Require literal syntax when initializing empty or zero Python builtin types.
	- `check-case-conflict` - Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
	- `check-docstring-first` - Checks for a common error of placing code before the docstring.
	- `check-merge-conflict` - Check for files that contain merge conflict strings.
	- `check-json` - Attempts to load all json files to verify syntax.
	- `check-toml` - Attempts to load all TOML files to verify syntax.
	- `check-yaml` - Attempts to load all yaml files to verify syntax.
	- `end-of-file-fixer` - Makes sure files end in a newline and only a newline.
	- `mixed-line-ending` - Replaces or checks mixed line ending.
	- `trailing-whitespace` - Trims trailing whitespace.
	- `check-vcs-permalinks` - Ensures that links to vcs websites are permalinks.
	- `check-shebang-scripts-are-executable` - Checks that scripts with shebangs are executable.
- [pygrep-hooks](https://github.com/pre-commit/pygrep-hooks) -  regex based pre-commit hooks. For more hooks, check [this](https://github.com/pre-commit/pygrep-hooks#provided-hooks)
	- `python-no-log-warn` - A quick check for the deprecated `.warn()` method of python loggers
	- `python-use-type-annotations` - Enforce that python3.6+ type annotations are used instead of type comments
- [pycln](https://github.com/hadialqattan/pycln) - A formatter for finding and removing unused import statements
- [black](https://github.com/psf/black) - Python code formatter.
- [isort](https://github.com/PyCQA/isort) - Sort imports alphabetically, and automatically separated into sections and by type

The only thing that is needed is adding `pre-commit` as a hook to Git and create a config similar to this:

<details>

<summary><code>.pre-commit-config.yaml</code></summary>

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        exclude: output|data
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: output|data
        args: ["--profile", "black"]
```
</details>

---
I can work on adding `pre-commit` after I get approval for adding this feature.

### PR DESCRIPTION
**Pull request by sudomaze**
## Description

I have added `pre-commit` to the development pipeline to ensure the quality of commits. Please refer to this issue (#1598) for more information

Fixes #1598

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Feature/Issue validation/testing

I have added `pre-commit` into a new environment and managed to have to work then tested on a new environment with a fresh clone from the original branch to test whether the instructions worked when followed to enable `pre-commit`.

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
I have tested the code by running `pre-commit` on a new environment with a fresh clone of the original repo.

- [x] Has code been commented, particularly in hard-to-understand areas?
I have added comments to `.pre-commit-config.yaml` and other comments could be referenced to this issue #1598 

- [x] Have you made corresponding changes to the documentation?
I have updated `CONTRIBUTING.md` to add an additional command to enable `pre-commit` during development.

---
Updated to add more information to `Checklist`.

### CODE REVIEW

**Comment by msaroufim** [comment]
Hi @sudomaze can you confirm whether this will only run on files modified in the current commit

**Comment by sudomaze** [comment]
I can confirm that `pre-commit` is only triggered when files are added using `git add` and `pre-commit` is triggered after running `git commit` which will look into those files that were added and apply what `.pre-commit-config.yaml` contains from checkers and formaters. 

When one of `pre-commit` tests fail, `pre-commit` will automatically make the required change or suggest changes to pass the test.

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
Since we're doing this here, do you mind updating https://github.com/pytorch/serve/blob/master/pull_request_template.md

If not I can do it in another PR

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
GPU CI can sometimes be flaky so feel free to run `git commit --allow-empty -m "Trigger Build"`

We're moving to Github Actions in a few days so this problem should go away

@lxning @maaquib can we get a stamp?

**Review by HamidShojanazeri — APPROVED** [review]

**Review by maaquib — APPROVED** [review]

**Pull request merged**
