### PR TITLE
Fix the early terminative issue in httpRequestHandlerChain

### LINKED ISSUE #1174: Torchserve 0.4.0 model & workflow management api unreachable
Hi,

I tried to start torchserve in a container but failed. Here is my config
```
cat ts.config
# Based on https://github.com/pytorch/serve/blob/master/docs/configuration.md
enable_envvars_config=true
decode_input_request=false
load_models=ALL
default_response_timeout=60
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8080
```
inference api and management api are sharing the same port. This is the common setting in AWS SageMaker.
torchserve  start cmd
```
torchserve --start --model-store ./ --ts-config ./sagemaker-ts.properties --models model.mar
```
I don't have `model.mar` in the `model-store` folder and just want to register models on the fly. However, I was not able to access `/models` or `/workflow`. When running
```
curl localhost:8080/models
```
I got
```
{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}
```
This is pretty wired error since I am just trying to list available models and this api is clearly documented.

## Context

Torchserve branch: dev

torchserve==0.4.0
torch-model-archiver==0.4.0

Python version: 3.8 (64-bit runtime)
Python executable: /home/ubuntu/miniconda3/envs/py38/bin/python

Versions of relevant python libraries:
captum==0.4.0
future==0.18.2
numpy==1.21.1
nvgpu==0.9.0
psutil==5.8.0
pygit2==1.6.1
pylint==2.6.0
pytest==6.2.4
pytest-cov==2.12.1
pytest-mock==3.6.1
requests==2.26.0
sentencepiece==0.1.96
torch==1.9.0+cpu
torch-model-archiver==0.4.0b20210721
torch-workflow-archiver==0.1.0b20210721
torchaudio==0.9.0
torchserve==0.4.0b20210721
torchtext==0.10.0
torchvision==0.10.0+cpu
transformers==4.6.0
wheel==0.36.2
torch==1.9.0+cpu
torchtext==0.10.0
torchvision==0.10.0+cpu
torchaudio==0.9.0

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: N/A
CMake version: N/A

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: default
* What kind of model is it e.g. vision, text, audio?: None
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: No
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:

```
# Based on https://github.com/pytorch/serve/blob/master/docs/configuration.md
enable_envvars_config=true
decode_input_request=false
load_models=ALL
default_response_timeout=60
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8080
```
* Link to your project [if any]:

## Expected Behavior

```
curl localhost:8080/models
{
  "models": []
}
```

## Current Behavior

```
curl localhost:8080/models
{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}
```

## Possible Solution

This is a bug in Torchserve 0.4.0 after introducing workflow api. With the config file, both inference and management api will share the same port. This will force `connector.ALL` in https://github.com/pytorch/serve/blob/7b1c6007cce0b4ed2caa2c20851b547b8827bee9/frontend/server/src/main/java/org/pytorch/serve/ModelServer.java#L386

The resultant `httpRequestHandlerChain` will have four elements
```
InferenceRequestHandler
WorkflowInferenceRequestHandler
ManagementRequestHandler
WorkflowMgmtRequestHandler
```
and they will be executed in order. However in `WorkflowInferenceRequestHandler` at https://github.com/pytorch/serve/blob/7b1c6007cce0b4ed2caa2c20851b547b8827bee9/frontend/server/src/main/java/org/pytorch/serve/workflow/api/http/WorkflowInferenceRequestHandler.java#L48 all `segments` with length shorter than three will be given `ResourceNotFoundException`. In this case, `/models` api call should be handled by `ManagementRequestHandler` after `WorkflowInferenceRequestHandler`. But `WorkflowInferenceRequestHandler` directly throw `ResourceNotFoundException` since `/models` call comes with length of 2.

The principle of throwing `ResourceNotFoundException` isn't quite correct here. This exception will break the handler chain and should only be thrown just before handing action, i.e. 100% sure that this api call should be handled here in this function. Or it should pass the handling logic to subsequent handler in the chain. 

## Steps to Reproduce
As shown in the beginning of this issue.

## Failure Logs [if any]

```
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
2021-07-17 03:03:34,383 [INFO ] pool-1-thread-1 ACCESS_LOG - /127.0.0.1:41674 "GET /ping HTTP/1.1" 200 16
2021-07-17 03:03:34,384 [INFO ] pool-1-thread-1 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:ff48916ebbf5,timestamp:null
2021-07-17 03:03:46,250 [INFO ] epollEventLoopGroup-3-2 ACCESS_LOG - /127.0.0.1:41676 "GET /models HTTP/1.1" 404 2
2021-07-17 03:03:46,250 [INFO ] epollEventLoopGroup-3-2 TS_METRICS - Requests4XX.Count:1|#Level:Host|#hostname:ff48916ebbf5,timestamp:null
2021-07-17 03:04:23,464 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:ff48916ebbf5,timestamp:1626491063
2021-07-17 03:04:23,465 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:8.87264633178711|#Level:Host|
```

### PR DESCRIPTION
**Pull request by Silas606**
## Description

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1174 
## Type of change
minor code change.
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Tested with
```
curl localhost:8080/ping
curl localhost:8080/models
curl localhost:8080/workflow
```

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Review by lxning — APPROVED** [review]

**Comment by maaquib** [comment]
@Silas606 Thanks fot this. Do you mind also adding the output of the sanity suite run as well ([doc](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTZiMTZiOTAtMGFkOS00OGQ0LWFkY2YtYTc2OTNmY2UxNGYw%40thread.v2/0?context=%7b%22Tid%22%3a%2243083d15-7273-40c1-b7db-39efd9ccc17a%22%2c%22Oid%22%3a%227bdf99af-f2a2-4b84-8263-377e0f9047ca%22%7d))

**Comment by Silas606** [comment]
Hi @maaquib here is the output of `torchserve_sanity.py`. The `doc` in your reply linked to a Team meeting which I don't have access to. I just attach the log here. Thanks.
[out.log](https://github.com/pytorch/serve/files/6890475/out.log)

**Comment by chauhang** [comment]
@lxning Can you please clarify why the same port is being used for the Management and Inference APIs? And how is this fix addressing the issue?

**Comment by Silas606** [comment]
Sorry I think I made a mistake here as mentioned in https://github.com/pytorch/serve/issues/1174#issuecomment-888260226

No changes needed in `ManagementRequestHandler.java` as it's not blocking anyone. The issue is just with `WorkflowInferenceRequestHandler.java`

@chauhang The fix in `WorkflowInferenceRequestHandler.java` simply follows rules in `InferenceRequestHandler.java` to only throw `ResourceNotFoundException` when this API request should clearly be handled here by moving the segment length check after confirming segments[1] equals `wfpredict`. others such as `/models` will be handed to subsequent handlers. 

Currently in 0.4.0, `WorkflowInferenceRequestHandler` will throw `ResourceNotFoundException` for any API requests with `segments.length<3` without considering subsequent handlers. With different API ports, that's OK for now since `WorkflowInferenceRequestHandler` itself is the last handler in inference chain. This logic seems a bit weird to me for a handler in chain though it can work properly. However, when sharing the same port between inference and management API, it will terminate the single chain early and `localhost:8080/models` just falls in this category. Thus those 404 errors.

I think sharing port is working fine for `0.3.1` and it would be reasonable to expect sharing API port to work also in `0.4.0` or later versions ? Do you have plans to deprecate this feature or are there any concerns with sharing API port ? Really appreciate your help.

**Comment by Silas606** [comment]
I have updated the commit to drop changes in `ManagementRequestHandler.java` and here is the sanity output [out_3ef7b7f.log](https://github.com/pytorch/serve/files/6893959/out_3ef7b7f.log)

**Review by chauhang — APPROVED** [review]

**Pull request merged**
