### PR TITLE
HPU requirements config file

### PR DESCRIPTION
**Pull request by RafLit**
## Description

In #3230 vllm was added to requirements/common.txt. 
Installation of vllm automatically installs an exact version of pytorch and overwrites our version.
We propose to add a parameter to install dependencies from a separate configuration for hpu.
Alternatively, moving vllm away from the common requirements file should also be considered.

## Type of change

- requirements/hpu.txt with gaudi dependencies was added,
- `--hpu` flag was added to ts_scripts/install_dependencies.py instead of `--skip_torch_install` as torch was eventually installed by vllm anyway.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by RafLit** [comment]
@agunapal could you please review this?

**Comment by agunapal** [comment]
> @agunapal could you please review this?

Hi @RafLit We'll have to discuss internally where to place vllm. We'll have a similar challenge with TensorRT(trt-llm)

But I like this idea of having a separate requirements file, at least for different GPU HWs. But the question that would still remain is..who will update this file? We get alerts when new versions of these libraries are released. Would you be updating them?.

**Comment by agunapal** [comment]
Hi @RafLit Closing this PR since we removed the dependency on vllm. Please check and confirm

**Comment by RafLit** [comment]
@agunapal Hi, we might be interested in the future in having a separate file for dependencies for our hardware and we could update it. For now this can remain closed, Thank you!

**Pull request closed without merging**
