### PR TITLE
Fixes dead links

### PR DESCRIPTION
**Pull request by NeoKish**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #pytorch/pytorch.github.io#1034

### CODE REVIEW

**Comment by msaroufim** [comment]
Hi @NeoKish would you be interested in contributing a linter to fix this problem once and for all?

Basically here https://github.com/pytorch/serve/blob/master/.github/workflows/lint.yml we can run a check to read `.md` files and in that md check if there's any non absolute links

Would also be very useful for us to later also integrate spell checking in documentation. Let me know if this is interesting to you

**Comment by NeoKish** [comment]
@msaroufim , I am interested in contributing a linter to fix the problem once and for all and and I have seen the issues of dead/broken links piling up in the pytorch.github.io repo. As I don't have any experience with linters before, I would like to work on it first and then get back to you with the contribution PR. This might take some time. Let me know if that's okay.

**Review by msaroufim — APPROVED** [review]

**Comment by maaquib** [comment]
@NeoKish [This](https://github.com/pytorch/serve/blob/master/ts_scripts/sanity_utils.py#L16) is a good starting point. We do have link checking but we don't fail the build on it. A lot of times we do get 429s from github on valid links due to the number of links we are checking.

**Comment by NeoKish** [comment]
@maaquib, Thanks for the link. Will check it out.

**Comment by NeoKish** [comment]
@msaroufim , Is the linter issue for broken links and typos still open or is it fixed? And if it is open, can I work on it?

**Pull request merged**
