### PR TITLE
Refactored UT for better reporting

### PR DESCRIPTION
**Pull request by harshbafna**
Addresses the concern raised in #158 related to UT reporting.

Updated UT reports for ModelServerTest and SnapshotTest

ModelServerTest Report

Snapshot Test Report

### CODE REVIEW

**Comment by mycpuorg** [comment]
@harshbafna this https://github.com/pytorch/serve/pull/159#issuecomment-619097149 failed a few days ago. Can you revisit this?

**Comment by harshbafna** [comment]
> [#159 (comment)](https://github.com/pytorch/serve/pull/159#issuecomment-619097149) failed please revisit and test on the latest top of tree

Rebased the branch to staging_0_1_1 and updated the branch. The latest CI build passed successfully.

**Comment by harshbafna** [comment]
> Please resolve conflicts.

Done.

**Comment by harshbafna** [comment]
> LGTM. Please resolve anymore merge conflicts. As long as future updates are limited to conflict resolution please go ahead and merge once resolved and CI success.
> 
> @harshbafna please include what was tested with this PR (should accompany every PR) and what the new reporting after this PR looks like (please include a copy here)

@mycpuorg  : Resolved the conflicts and add the screenshots of reports in the main description of the PR.

**Comment by mycpuorg** [comment]
@harshbafna this is good. Can you look into a way to automate including this report for each nightly test (along with the end-to-end regression test reports)?

**Comment by mycpuorg** [comment]
Consult with @dhanainme @maaquib

**Pull request merged**
