### PR TITLE
Fixed typo in ModelConfig.java

### PR DESCRIPTION
**Pull request by arnavmehta7**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

Corrected the documentation, it had to be "milliseconds" not "million seconds"

## Checklist:

- [x] Did you have fun?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Review by agunapal — APPROVED** [review]

**Comment by agunapal** [comment]
Hi @arnavmehta7  Could you please check the errors in the CI runs

**Comment by arnavmehta7** [comment]
Oh @agunapal, Thanks for reminder. Looks very strange. let me see the difference between my branch and master

**Comment by arnavmehta7** [comment]
```
Traceback (most recent call last):
  File "torchserve_sanity.py", line 65, in <module>
    torchserve_sanity()
  File "torchserve_sanity.py", line 46, in torchserve_sanity
    cleanup()
  File "torchserve_sanity.py", line 50, in cleanup
    ts.stop_torchserve()
  File "/home/ubuntu/actions-runner/_work/serve/serve/ts_scripts/tsutils.py", line 98, in stop_torchserve
    p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=STDOUT)
  File "/home/ubuntu/actions-runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/actions-runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'torchserve'
Error: Final attempt failed. Child_process exited with error code 1
```

Strange. Doesn't seems to be through my changes @agunapal.

**Comment by agunapal** [comment]
@arnavmehta7 

This looks like the reason 

```
> Task :archive:pmdMain
Unable to exclude rules [DoNotCallSystemExit, MissingBreakInSwitch] from ruleset reference category/java/errorprone.xml; perhaps the rule name is misspelled or the rule doesn't exist anymore?
4 PMD rule violations were found. See the report at: file:///home/runner/work/serve/serve/frontend/archive/build/reports/pmd/main.html

> Task :archive:pmdTest SKIPPED
> Task :archive:verifyJava FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/runner/work/serve/serve/frontend/tools/gradle/formatter.gradle' line: 57

* What went wrong:
Execution failed for task ':archive:verifyJava'.
> File not formatted: /home/runner/work/serve/serve/frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
```

**Comment by arnavmehta7** [comment]
Oh I am sorry. Fixing

**Comment by arnavmehta7** [comment]
@agunapal Sorry, I've been trying to read the contributions. However there is no information on the "formatter". Somehow, my formatter formats files differently, are there any guidelines to help me out?
Thanks!

**Comment by arnavmehta7** [comment]
@agunapal 
```
FILE: ./ts/tests/README.md
No hyperlinks found!
```
It's regarding markdowns, I think this is not related to my change right?

**Pull request merged**
