### PR TITLE
fix batch input - Nvidia DALI

### PR DESCRIPTION
**Pull request by jagadeeshi2i**
## Description
Adds fix for batch input support

## Type of change
Modify custom handler to support batch input

[ts_log.log](https://github.com/pytorch/serve/files/12012120/ts_log.log)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by agunapal** [comment]
Hi @jagadeeshi2i  Could you please try running the benchmark tool with your changes.

Few weeks ago, I tried this and I was noticing issues with mismatch related to expected batch_size response and the actual response.

**Review by agunapal — COMMENTED** [review]
Hi @jagadeeshi2i Could you please try running the benchmark tool with your changes.

Few weeks ago, I tried this and I was noticing issues with mismatch related to expected batch_size response and the actual response.

**Comment by jagadeeshi2i** [comment]
> Hi @jagadeeshi2i Could you please try running the benchmark tool with your changes.
> 
> Few weeks ago, I tried this and I was noticing issues with mismatch related to expected batch_size response and the actual response.

Hi @agunapal I have added the model_metrics.log from benchmark tool.

**Review by agunapal — CHANGES_REQUESTED** [review]
Hi @jagadeeshi2i  I am guessing you have some uncommitted changes.

I tried your example

Getting this error

```
2023-07-13T23:02:21,869 [INFO ] W-9000-resnet-18_1.0-stdout MODEL_LOG -     response = self.pipe.run(source=batch_tensor)
2023-07-13T23:02:21,869 [INFO ] W-9000-resnet-18_1.0-stdout MODEL_LOG - TypeError: Pipeline.run() got an unexpected keyword argument 'source'
```

**Comment by jagadeeshi2i** [comment]
> Hi @jagadeeshi2i I am guessing you have some uncommitted changes.
> 
> I tried your example
> 
> Getting this error
> 
> ```
> 2023-07-13T23:02:21,869 [INFO ] W-9000-resnet-18_1.0-stdout MODEL_LOG -     response = self.pipe.run(source=batch_tensor)
> 2023-07-13T23:02:21,869 [INFO ] W-9000-resnet-18_1.0-stdout MODEL_LOG - TypeError: Pipeline.run() got an unexpected keyword argument 'source'
> ```

You have to re build the model.dali file.

**Comment by agunapal** [comment]
@jagadeeshi2i 
Yes I did.

```
(torchserve) ubuntu@ip-172-31-7-107:~/fork/serve/examples/nvidia_dali$ python serialize_dali_pipeline.py --config dali_config.json
/home/ubuntu/anaconda3/envs/torchserve/lib/python3.10/site-packages/nvidia/dali/backend.py:46: Warning: DALI support for Python 3.10 is experimental and some functionalities may not work.
  deprecation_warning("DALI support for Python 3.10 is experimental and some functionalities "
Saved ./model.dali
(torchserve) ubuntu@ip-172-31-7-107:~/fork/serve/examples/nvidia_dali$ torch-model-archiver --model-name resnet-18 --version 1.0 --model-file ../image_classifier/resnet_18/model.py --serialized-file resnet18-f37072fd.pth --handler custom_handler.py --extra-files ../image_classifier/index_to_name.json,./model.dali,./dali_config.json
(torchserve) ubuntu@ip-172-31-7-107:~/fork/serve/examples/nvidia_dali$ mkdir model_store
(torchserve) ubuntu@ip-172-31-7-107:~/fork/serve/examples/nvidia_dali$ mv resnet-18.mar model_store/
(torchserve) ubuntu@ip-172-31-7-107:~/fork/serve/examples/nvidia_dali$ 
(torchserve) ubuntu@ip-172-31-7-107:~/fork/serve/examples/nvidia_dali$ 

```

I will try it again and update

**Comment by agunapal** [comment]
[dali_logs.txt](https://github.com/pytorch/serve/files/12098929/dali_logs.txt)

hi @jagadeeshi2i  I tried it again. I see the same error. I have attached the complete log. Can you please check

**Comment by jagadeeshi2i** [comment]
> [dali_logs.txt](https://github.com/pytorch/serve/files/12098929/dali_logs.txt)
> 
> hi @jagadeeshi2i I tried it again. I see the same error. I have attached the complete log. Can you please check

Sorry my bad. I have updated the requirements.txt file to point the latest dali version.

**Review by agunapal — APPROVED** [review]
Thanks @jagadeeshi2i I tried it. It works.

**Review by msaroufim — APPROVED** [review]
Stamping to unblock I did not test

**Pull request merged**
