### PR TITLE
Fix typo: vesion -> version, succsesfully -> successfully

### PR DESCRIPTION
**Pull request by tadayosi**
## Description

Hi, thank you for merging my previous PR. This is yet another typo fix PR. What it does is:
- `vesion` -> `version`
- `succsesfully` -> `successfully`

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

n/a

## Checklist:

- [x] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by tadayosi** [comment]
Could anybody take a look at this? @mreso? Thank you!

**Review by mreso — APPROVED** [review]
LGTM

**Comment by mreso** [comment]
Thanks @tadayosi for contributing!

**Comment by mreso** [comment]
Was hoping we can merge without the docker checks... This is blocked right now, as we need to merge #3327 first

**Pull request merged**
