### PR TITLE
added bert models in sanity script

### LINKED ISSUE #480: Add GPU tests to the Automation test framework
To catch the regression issues on GPU side, please add support for running the Automation test suite on GPU machines in addition to the current tests on CPUs.  GPU tests can run daily or few times a week.

## Is your feature request related to a problem? Please describe.
The issue with BERT example not running on GPU would have been caught sooner, if the tests were in place. 

## Describe the solution
Spin up GPU instance and run all the tests on GPU. In case the frequency on GPU tests is not the same as the CPU tests, in the Tests/readme page add another status tag for GPU tests success/failure and link to last run tests with the timestamp.

## Describe alternatives solution
None

### PR DESCRIPTION
**Pull request by harshbafna**
## Description

Added all 6 birt models in sanity script

Fixes #480

**Note**: Need to wait for #479 to get fixed before this can be merged to master. The new mar files will also need to be updated in the public S3 bucket.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Check build logs on CPU and GPU which executes the `torchserve_sanity.sh` script

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by maaquib** [comment]
CI failure

```
2020-07-06 19:56:43,788 [INFO ] W-9004-roberta_qa_torchscript_1.0 ACCESS_LOG - /127.0.0.1:56982 "POST /models?url=https://torchserve.s3.amazonaws.com/mar_files/roberta_qa_torchscript.mar&initial_workers=1&synchronous=true&model_name=roberta_qa_torchscript HTTP/1.1" 200 19027
2020-07-06 19:56:43,788 [INFO ] W-9004-roberta_qa_torchscript_1.0 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:a0658957b977,timestamp:null
2020-07-06 19:56:43,788 [DEBUG] W-9004-roberta_qa_torchscript_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-roberta_qa_torchscript_1.0 State change WORKER_STARTED -> WORKER_MODEL_LOADED
2020-07-06 19:56:43,789 [INFO ] W-9004-roberta_qa_torchscript_1.0 TS_METRICS - W-9004-roberta_qa_torchscript_1.0.ms:7883|#Level:Host|#hostname:a0658957b977,timestamp:1594065403
+ response=200
+ '[' '!' 200 == 200 ']'
+ echo 'Successfully registered roberta_qa_torchscript model with torchserve'
Successfully registered roberta_qa_torchscript model with torchserve
+ run_inference roberta_qa_torchscript examples/Huggingface_Transformers/sample_text.txt
+ for i in {1..4}
+ echo 'Running inference on roberta_qa_torchscript model'
Running inference on roberta_qa_torchscript model
++ curl --write-out '%{http_code}' --silent --output /dev/null --retry 5 -X POST http://localhost:8080/predictions/roberta_qa_torchscript -T examples/Huggingface_Transformers/sample_text.txt
2020-07-06 19:56:43,812 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Received text: '{"question" :"Who was Jim Henson?", "context": "Jim Henson was a nice puppet"}
2020-07-06 19:56:43,812 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - '
2020-07-06 19:56:43,812 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Invoking custom service failed.
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/usr/local/lib/python3.6/dist-packages/ts/service.py", line 100, in predict
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 435
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     ret = self._entry_point(input_batch, self.context)
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/tmp/models/2cc7d51f6aa87fe57805789272ca164ace0f1f17/Transformer_handler_generalized.py", line 168, in handle
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     raise e
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/tmp/models/2cc7d51f6aa87fe57805789272ca164ace0f1f17/Transformer_handler_generalized.py", line 163, in handle
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     data = _service.inference(data)
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/tmp/models/2cc7d51f6aa87fe57805789272ca164ace0f1f17/Transformer_handler_generalized.py", line 125, in inference
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     answer_start_scores, answer_end_scores = self.model(input_ids)
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     result = self.forward(*input, **kwargs)
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - The above operation failed in interpreter.
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Serialized   File "code/__torch__/transformers/modeling_roberta.py", line 8
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   def forward(self: __torch__.transformers.modeling_roberta.RobertaForQuestionAnswering,
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     input_ids: Tensor) -> Tuple[Tensor, Tensor]:
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _0 = (self.qa_outputs).forward((self.roberta).forward(input_ids, ), )
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -                                     ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     start_logits, end_logits, = torch.split(_0, 1, -1)
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _1 = (torch.squeeze(start_logits, -1), torch.squeeze(end_logits, -1))
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Serialized   File "code/__torch__/transformers/modeling_roberta.py", line 35, in forward
2020-07-06 19:56:44,247 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _12 = torch.to(extended_attention_mask, 6, False, False, None)
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     attention_mask0 = torch.mul(torch.rsub(_12, 1., 1), CONSTANTS.c0)
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _13 = (_3).forward((_4).forward(input_ids, input, ), attention_mask0, )
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -                         ~~~~~~~~~~~ <--- HERE
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _14 = (_2).forward(_13, )
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _13
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Serialized   File "code/__torch__/transformers/modeling_roberta.py", line 61, in forward
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     input0 = torch.to(_22, dtype=4, layout=0, device=torch.device("cpu"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _23 = (_19).forward(input_ids, )
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _24 = (_18).forward(input0, )
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -            ~~~~~~~~~~~~ <--- HERE
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _25 = (_17).forward(input, )
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     input1 = torch.add(torch.add(_23, _24, alpha=1), _25, alpha=1)
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/functional.py(1724): embedding
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/sparse.py(112): forward
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(534): _slow_forward
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0 ACCESS_LOG - /127.0.0.1:38688 "POST /predictions/roberta_qa_torchscript HTTP/1.1" 503 437
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(548): __call__
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:a0658957b977,timestamp:null
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/transformers/modeling_bert.py(174): forward
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/transformers/modeling_roberta.py(64): forward
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(534): _slow_forward
2020-07-06 19:56:44,248 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(548): __call__
2020-07-06 19:56:44,248 [DEBUG] W-9004-roberta_qa_torchscript_1.0 org.pytorch.serve.wlm.Job - Waiting time: 1, Inference time: 437
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/transformers/modeling_bert.py(726): forward
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(534): _slow_forward
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(548): __call__
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/transformers/modeling_roberta.py(663): forward
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(534): _slow_forward
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/nn/modules/module.py(548): __call__
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/jit/__init__.py(1027): trace_module
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - /Users/hamidnazeri/.local/share/virtualenvs/serve--O1Lz67T/lib/python3.8/site-packages/torch/jit/__init__.py(873): trace
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Download_Transformer_models.py(60): transformers_model_dowloader
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Download_Transformer_models.py(74): <module>
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Serialized   File "code/__torch__/torch/nn/modules/sparse/___torch_mangle_0.py", line 7, in forward
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   def forward(self: __torch__.torch.nn.modules.sparse.___torch_mangle_0.Embedding,
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     input: Tensor) -> Tensor:
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     position_embeddings = torch.embedding(self.weight, input, 1, False, False)
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -                           ~~~~~~~~~~~~~~~ <--- HERE
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return position_embeddings
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - The above operation failed in interpreter.
2020-07-06 19:56:44,249 [INFO ] W-9004-roberta_qa_torchscript_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
+ response=
```

**Comment by harshbafna** [comment]
> @harshbafna Seeing CI failure for GPU. Logs below

@maaquib : These are expected failures on GPU and will get resolved once fix for #479  is added by @HamidShojanazeri .

This PR ensures that the bert model errors are caught in regular CI build.

**Comment by maaquib** [comment]
> > @harshbafna Seeing CI failure for GPU. Logs below
> 
> @maaquib : These are expected failures on GPU and will get resolved once fix for #479 is added by @HamidShojanazeri .
> 
> This PR ensures that the bert model errors are caught in regular CI build.

I'll hold off on merging this until there is a fix for #479

**Comment by HamidShojanazeri** [comment]
Hi all, the issue #479 got solved in https://github.com/pytorch/serve/pull/477 and I will upload the new .mar files in s3 buckets. Please let me know if any other changes I need to make. Thanks.

**Comment by harshbafna** [comment]
> Hi all, the issue #479 got solved in #477 and I will upload the new .mar files in s3 buckets. Please let me know if any other changes I need to make. Thanks.

Once the new mar files are uploaded in S3 bucket, the CI build for this PR should succeed. No other action items required.

**Pull request merged**
