### PR TITLE
fix workerthread hang due to grpc client cancel connection

### PR DESCRIPTION
**Pull request by lxning**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

GPRC service throw exception when it is trying to send response if GRPC client was already disconnected. This exception trigger workerthread is trying to shutdown. However, the shutdown is blocked due to GRPC server call lock.

Fixes #(issue)
#1815 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Follow the reproduce [steps](https://github.com/pytorch/serve/issues/1815#issuecomment-1238304905). 

1. start grpc client to send multiple inference request
2. stop grpc client 
3. start grpc client to send multiple inference request again

Result: workerthread 9000 keep alive
```
2022-09-09T20:08:27,915 [WARN ] W-9000-BERTSeqClassification_torchscript_1.0 org.pytorch.serve.job.Job - grpc client call already cancelled
2022-09-09T20:08:27,915 [WARN ] W-9000-BERTSeqClassification_torchscript_1.0 org.pytorch.serve.job.Job - grpc client call already cancelled
....
2022-09-09T20:08:34,483 [INFO ] W-9000-BERTSeqClassification_torchscript_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 298
```
[ts_log.log.zip](https://github.com/pytorch/serve/files/9541454/ts_log.log.zip)

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
Stamping to unblock, should we also integrate a test?

**Comment by hgong-snap** [comment]
Hi! just to understand the fix: will worker restart correctly(without hanging), or catch the exception and worker can alive ?

**Comment by lxning** [comment]
> Hi! just to understand the fix: will worker still restart(correctly without hanging), or catch the exception and worker can alive ? Asking because in high-throughput production use case, cancellation can be often, and frequent worker restart might result in frequent 'no worker error'.

@hgong-snap This fixing does not throw exception (only log warning "grpc client call already cancelled") so the worker is still alive and is able to process the incoming new request). The behind the philosophy is the worker is independent on front grpc handler(ie. client interruption).

**Comment by MHatemAbdelhamid** [comment]
Can someone review it as it is resolving a blocking issue @maaquib , @msaroufim

**Review by msaroufim — APPROVED** [review]
Stamping because this is urgent but wondering out loud if we should integrate a test case with an interrupt

**Pull request merged**
