### PR TITLE
fixing broken tests and docs after v1 and v2 kfserve examples

### PR DESCRIPTION
**Pull request by msaroufim**
In a recent PR https://github.com/pytorch/serve/pull/1429 we've introduced `v1` and `v2` directories for the `kserve` examples and this broke our postman tests and documentation

From `serve` run `grep -r "/kubernetes/kserve/kf_request_json" .`

And you'll see all the places where `v1` and `v2` directories were not added

I would check all these files and test to make sure there are no more issues https://gist.github.com/msaroufim/108d9a01d7cbea12eaccdfede20036d1

And https://github.com/pytorch/serve/tree/master/test/postman and look for any places with `v2 mentioned`

Important because this broke our regression tests when jsons were not found https://torchserve-regression-test.s3.amazonaws.com/public/latest/test_exec.log

I fixed the `v1` issues but not sure how to fix the `v2` issues since the files now look very different
Before: https://github.com/pytorch/serve/blob/f710bf1d66fe5971978efed42aa576df768b3137/kubernetes/kserve/kf_request_json/bert_v2.json
After: https://github.com/pytorch/serve/blob/master/kubernetes/kserve/kf_request_json/v2/bert/bert_tensor_v2.json

cc: @chauhang @shrinath-suresh 

Should probably detect this automatically in CI @nskool and block merging

### CODE REVIEW

**Comment by lxning** [comment]
@shrinath-suresh could you please submit regression test log after you change the code?

**Comment by shrinath-suresh** [comment]
> grep -r "/kubernetes/kserve/kf_request_json" .

Thanks @msaroufim for the v1 fix. I will work on the v2 items and keep this thread updated.

**Comment by shrinath-suresh** [comment]
> @shrinath-suresh could you please submit regression test log after you change the code?

Sure @lxning . Here after, i will run regression tests for all the PRs before merging.

**Comment by msaroufim** [comment]
@shrinath-suresh feel free to merge to this branch directly

**Comment by shrinath-suresh** [comment]
@msaroufim I have fixed the regression tests and created a WIP PR - https://github.com/pytorch/serve/pull/1464 targetting `kfservefix` branch. 

I have triggered the regression suite locally in my machine. Once all the tests are passed, i will remove the WIP tag. Post that i will work on changing the docs and readmes.

**Comment by lxning** [comment]
@shrinath-suresh Regression test still fails on kfservefix branch.  Please run the following steps at your local on branch kfservefix and submit regression test log.

1. git merge master
2. python test/regression_tests.py 2>&1|tee reg.txt

**Comment by shrinath-suresh** [comment]
> 2\. python test/regression_tests.py 2>&1|tee reg.txt

sure @lxning . Last night i triggered a run (ran in background with the command you shared) in my local branch. I dont see any AssertionError on postman tests. But the regression tests got struck after 25%. I have retriggered the build.

[regression_test.log](https://github.com/pytorch/serve/files/8138480/regression_test.log)

**Pull request closed without merging**
