### PR TITLE
issue templates

### PR DESCRIPTION
**Pull request by dhaniram-kshirsagar**
## Description

This PR adds issue templates for bug reports and feature requests. Hence following sections are NA here.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by dhaniram-kshirsagar** [comment]
@lokeshgupta1975 Let me know if this also needs to have help and doc related templates similar to [torchvision](https://github.com/pytorch/vision/tree/master/.github/ISSUE_TEMPLATE)

**Comment by lokeshgupta1975** [comment]
@dhaniram-kshirsagar Yes, it would be good to have doc related templates as well

**Comment by dhaniram-kshirsagar** [comment]
> @dhaniram-kshirsagar Yes, it would be good to have doc related templates as well

Done.

**Comment by dhanainme** [comment]
I was trying to test this in my local repo. I had to move the ISSUE_TEMPLATE folder in to a .github folder to get this working. 

My private repo : https://github.com/dhanainme/serve 
Documentation : https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser


	renamed:    ISSUE_TEMPLATE/bug_template.md -> .github/ISSUE_TEMPLATE/bug_template.md
	renamed:    ISSUE_TEMPLATE/doc_template.md -> .github/ISSUE_TEMPLATE/doc_template.md
	renamed:    ISSUE_TEMPLATE/feature_template.md -> .github/ISSUE_TEMPLATE/feature_template.md

Screen Shot 2020-05-14 at 10 57 05 AM

**Comment by maaquib** [comment]
> I was trying to test this in my local repo. I had to move the ISSUE_TEMPLATE folder in to a .github folder to get this working.
> 
> My private repo : https://github.com/dhanainme/serve
> Documentation : https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> 
> ```
> renamed:    ISSUE_TEMPLATE/bug_template.md -> .github/ISSUE_TEMPLATE/bug_template.md
> renamed:    ISSUE_TEMPLATE/doc_template.md -> .github/ISSUE_TEMPLATE/doc_template.md
> renamed:    ISSUE_TEMPLATE/feature_template.md -> .github/ISSUE_TEMPLATE/feature_template.md

@dhaniram-kshirsagar Can you move the files to .github folder as suggested by @dhanainme and I can merge

**Pull request merged**
