### PR TITLE
Fix for manual execution of test scripts and corresponding documentation

### LINKED ISSUE #824: old scripts folder references in multiple places
There are still references of the older "scripts" folder at multiple places in the code after the recent fix for https://github.com/pytorch/serve/issues/796  (install from source issue). Please resolve all references, you can check using this [query](https://github.com/pytorch/serve/search?q=%22.%2Fscripts%22)

### PR DESCRIPTION
**Pull request by harshbafna**
## Description

The script for installing dependencies was failing in case of manual execution and not the actual source related test cases/regression suite. The root cause is that 'sudo' command was not required on codebuild related machines hence codebuild sanity/regression works fine. However, when executed manually on any Linux instance, install dependencies related commands needs to be invoked with 'sudo'.

Fixes #824 #826 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Feature/Issue validation/testing

[docker_dev_build.txt](https://github.com/pytorch/serve/files/5636675/docker_dev_build.txt)
[regression suite DLAMI.txt](https://github.com/pytorch/serve/files/5636677/regression.suite.DLAMI.txt)
[regression suite plain ubuntu.txt](https://github.com/pytorch/serve/files/5636678/regression.suite.plain.ubuntu.txt)
[Sanity script DLAMI.txt](https://github.com/pytorch/serve/files/5636679/Sanity.script.DLAMI.txt)
[Sanity script plain ubuntu.txt](https://github.com/pytorch/serve/files/5636681/Sanity.script.plain.ubuntu.txt)

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by jeremiahschung** [comment]
@harshbafna thanks for putting up the fix. 

I ran some tests in a CPU based EC2 instance and ran into some issue. Can you please share your thoughts?

For regression_utils.py, Few warnings were logged at the end running. The tests all succeeded:
[regression_utils success with warnings - torchserve PR 827.txt](https://github.com/pytorch/serve/files/5638459/regression_utils.success.with.warnings.-.torchserve.PR.827.txt)

For api_utils.py, logging error happened after tests have finished successfully:
[api tests success with logging error - torchserve PR 827.txt](https://github.com/pytorch/serve/files/5638464/api.tests.success.with.logging.error.-.torchserve.PR.827.txt)

When I ran test/regression_tests.py, I ran into an import error.
```
ubuntu@ip-172-31-31-36:~/serve$ python test/regression_tests.py 
Traceback (most recent call last):
  File "test/regression_tests.py", line 10, in <module>
    from ts_scripts.regression_utils import test_regression
ModuleNotFoundError: No module named 'ts_scripts.regression_utils'
```

**Review by lxning — APPROVED** [review]

**Comment by abishekchiffon** [comment]
> When I ran test/regression_tests.py, I ran into an import error.

I encountered the same kind of import error while I run the test/regression_tests and torchserve_sanity. In specific python installations it works occasionally.

**Comment by harshbafna** [comment]
> @harshbafna thanks for putting up the fix.
> 
> I ran some tests in a CPU based EC2 instance and ran into some issue. Can you please share your thoughts?
> 
> For regression_utils.py, Few warnings were logged at the end running. The tests all succeeded:
> [regression_utils success with warnings - torchserve PR 827.txt](https://github.com/pytorch/serve/files/5638459/regression_utils.success.with.warnings.-.torchserve.PR.827.txt)
> 
> For api_utils.py, logging error happened after tests have finished successfully:
> [api tests success with logging error - torchserve PR 827.txt](https://github.com/pytorch/serve/files/5638464/api.tests.success.with.logging.error.-.torchserve.PR.827.txt)
> 
> When I ran test/regression_tests.py, I ran into an import error.
> 
> ```
> ubuntu@ip-172-31-31-36:~/serve$ python test/regression_tests.py 
> Traceback (most recent call last):
>   File "test/regression_tests.py", line 10, in <module>
>     from ts_scripts.regression_utils import test_regression
> ModuleNotFoundError: No module named 'ts_scripts.regression_utils'
> ```

@jeremiahschung:

We have fixed this issue. Could you please retest with the latest pull?

We have restored to only 3 main python scripts similar to what we had before the Windows merge :
 - torchserve_sanity.py (To run the sanity suite)
 - test/regression_test.py (To run the regression suite)
 - ts_scripts/install_from_src.py (For installing TorchServe and torch-model-archiver from source)
These main scripts will invoke the required functions from the rest of the utility scripts.
Note: 
 - There will be a pre-requisite to run install_dependencies.py before running any of the above scripts.
 - Rest of the scripts in ts_scripts package are no more self-executatble.

**Review by maaquib — APPROVED** [review]

**Comment by jeremiahschung** [comment]
> > @harshbafna thanks for putting up the fix.
> > I ran some tests in a CPU based EC2 instance and ran into some issue. Can you please share your thoughts?
> > For regression_utils.py, Few warnings were logged at the end running. The tests all succeeded:
> > [regression_utils success with warnings - torchserve PR 827.txt](https://github.com/pytorch/serve/files/5638459/regression_utils.success.with.warnings.-.torchserve.PR.827.txt)
> > For api_utils.py, logging error happened after tests have finished successfully:
> > [api tests success with logging error - torchserve PR 827.txt](https://github.com/pytorch/serve/files/5638464/api.tests.success.with.logging.error.-.torchserve.PR.827.txt)
> > When I ran test/regression_tests.py, I ran into an import error.
> > ```
> > ubuntu@ip-172-31-31-36:~/serve$ python test/regression_tests.py 
> > Traceback (most recent call last):
> >   File "test/regression_tests.py", line 10, in <module>
> >     from ts_scripts.regression_utils import test_regression
> > ModuleNotFoundError: No module named 'ts_scripts.regression_utils'
> > ```
> 
> @jeremiahschung:
> 
> We have fixed this issue. Could you please retest with the latest pull?
> 
> We have restored to only 3 main python scripts similar to what we had before the Windows merge :
> 
> * torchserve_sanity.py (To run the sanity suite)
> * test/regression_test.py (To run the regression suite)
> * ts_scripts/install_from_src.py (For installing TorchServe and torch-model-archiver from source)
>   These main scripts will invoke the required functions from the rest of the utility scripts.
>   Note:
> * There will be a pre-requisite to run install_dependencies.py before running any of the above scripts.
> * Rest of the scripts in ts_scripts package are no more self-executatble.

Thanks @harshbafna, I'll continue testing and report my findings in the relevant PRs or issues. (currently testing https://github.com/pytorch/serve/pull/836)

**Pull request merged**
