### PR TITLE
Fixed Text2Speech synthesis as NVIDIA models' URL required an update

### LINKED ISSUE #761: Cannot create model archive in waveglow example
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context
While creating model archive file for waveglow example the create_mar.sh script fails with 404 error.

```
+ wget https://api.ngc.nvidia.com/v2/models/nvidia/tacotron2pyt_fp32/versions/1/files/nvidia_tacotron2pyt_fp32_20190306.pth
--2020-10-29 15:08:01--  https://api.ngc.nvidia.com/v2/models/nvidia/tacotron2pyt_fp32/versions/1/files/nvidia_tacotron2pyt_fp32_20190306.pth
Resolving api.ngc.nvidia.com (api.ngc.nvidia.com)... 54.213.120.107, 54.186.38.188
Connecting to api.ngc.nvidia.com (api.ngc.nvidia.com)|54.213.120.107|:443... connected.
HTTP request sent, awaiting response... 404 
2020-10-29 15:08:02 ERROR 404: (no description)
```

* torchserve version:
* torch version:1.6.0
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version: Ubuntu 16.04 64bit

## Your Environment
* Installed using source? [yes/no]:no
* Are you planning to deploy it using docker container? [yes/no]:yes
* Is it a CPU or GPU environment?:GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:audio
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Possible Solution
Fix the broken links

## Steps to Reproduce

1. Navigate to waveglow example in torchserve
2. Run create_mar.sh script
...

### PR DESCRIPTION
**Pull request by alvarobartt**
## Description

As the NVIDIA Waveglow and Tacotron2 PyTorch pre-trained models have been updated, their URLs too and the previous versions of those models seem to be unavailable, so that the URLs required an update.

This fix should probably be applied to all NVIDIA model URLs in case they do not work. As the previous URLs are currently unavailable, the error code while trying to retrieve those either using `wget` or `curl` is HTTP 404.

More information regarding all the NVIDIA Catalog Models can be found at: https://ngc.nvidia.com/catalog/models?orderBy=modifiedDESC&pageNumber=1&query=&quickFilter=models&filters=

Fixes #761 

References shared by @harshbafna that should probably be also fixed:
- NVIDIA/DeepLearningExamples#725
- NVIDIA/DeepLearningExamples#721

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by harshbafna — CHANGES_REQUESTED** [review]
@alvarobartt: The tacotron2 and waveglow model weight file names are being changed here which are used in waveglow handler, due to which the model registration will fail.

Please update the handler as well.

**Comment by alvarobartt** [comment]
You're right @harshbafna I forgot to commit those changes... Now everything should be right! 👍🏻

**Review by alvarobartt — COMMENTED** [review]
Updated handler refs to the updated version of Waveglow and Tacotron2 NVIDIA models as requested by @harshbafna

**Comment by chauhang** [comment]
@alvarobartt Can you please check if picking the waveglow/tacotron2 models from PyTorch Hub might be a better option, so that we don't have to deal with breaking path changes in future?

https://pytorch.org/hub/nvidia_deeplearningexamples_waveglow/
https://pytorch.org/hub/nvidia_deeplearningexamples_tacotron2/

**Comment by alvarobartt** [comment]
Hi @chauhang! Yes, indeed that's a better option/way to proceed, the thing is that the NVIDIA DeepLearning examples repository on the branch torchhub is also facing the same issue, which means that the `torch.hub.load()` function of those models won't work... Anyway, I submitted a PR to [NVIDIA/DeepLearningExamples](https://github.com/NVIDIA/DeepLearningExamples) that you can find at NVIDIA/DeepLearningExamples#727 👍🏻

**Comment by alvarobartt** [comment]
Quick update! It seems that people from NVIDIA already solved this using some temp fallback to backup model checkpoints for all the models mentioned above (Tacotron2, Waveglow) and also for SSD. As you can see at https://github.com/NVIDIA/DeepLearningExamples/commit/3e961c3a149e0f6e4ce752fc1b7ddef0fbb3d9e1 So on, this issue regarding `torch.hub.load` seems to be temporarily fixed (I guess they discarded my PR as they included those new temporary URLs) but not quite sure about that.

Anyway, tomorrow I will likely update the URLs for the Tacotron2 and Waveglow model checkpoints downloaded in the `create_mar.sh` file as well as the names of those models in the `waveglow_handler.py`. So maybe currently this should be merged using those URLs, but maybe an issue should be kept open so as to get back to this once NVIDIA properly updates its model URLs so that the `torch.hub.load()` function works as expected, even though it currently does with this temporary fix they made.

**Review by alvarobartt — COMMENTED** [review]
Created `requirements.txt` for Waveglow as requested by @chauhang and @harshbafna in https://github.com/pytorch/serve/issues/761, so as to avoid its manual installation on the server as TorchServe already handles this via that file on the MAR.

**Review by chauhang — APPROVED** [review]

**Review by harshbafna — APPROVED** [review]

**Pull request merged**
