### PR TITLE
Update .gitignores

### LINKED ISSUE #1850: A few typos, need to do some lints and update .gitignores
Regarding lint, I mean to apply existing pre-commit hooks to the code

### PR DESCRIPTION
**Pull request by sadra-barikbin**
## Description

Some typos are fixed. And some lints.

Fixes #1850 

## Checklist:

- [x] Did you have fun?

### CODE REVIEW

**Comment by msaroufim** [comment]
Thanks @sadra-barikbin I'd like us to stop merging fixes for typos and instead expand our linter with broken link detection and typo detection (see ts_scripts/spellcheck.sh)

If you only keep the `.gitignore` changes I'd be happy to merge this and if you'd like to do a followup PR on linting would be happy to give guidance and help merge

**Comment by sadra-barikbin** [comment]
I did. Regarding linting, you mean to add some other pre-commit hooks?

**Comment by msaroufim** [comment]
Yup exactly! 
pre-commit hooks would need to look at files that were changed and fix any typos in them and/or find any broken links after doc build is performed

Relevant links are
* https://github.com/pytorch/serve/blob/master/.github/workflows/lint.yml
* https://github.com/pytorch/serve/blob/master/.github/workflows/doc-automation.yml
* https://github.com/pytorch/serve/blob/master/ts_scripts/spellcheck.sh
* https://github.com/pytorch/serve/blob/master/link_check_config.json

**Review by msaroufim — APPROVED** [review]

**Comment by sadra-barikbin** [comment]
@msaroufim , I created the PR to add linting steps:
https://github.com/pytorch/serve/pull/1855.

By the way don't you want to add typing info to `ts`, at least? Aside from code quality, it eases usage of the library. Personally, I had hard time making a custom handler (in terms of exact type and format of its inputs/outputs).

**Comment by msaroufim** [comment]
I've been wanting to add types for a a while. Would you like to setup typing for a single file? Also I won't be able to merge a PR that adds types for all files so the workflow needs to be progressive the same way our linting is

**Comment by sadra-barikbin** [comment]
> I've been wanting to add types for a a while. Would you like to setup typing for a single file? Also I won't be able to merge a PR that adds types for all files so the workflow needs to be progressive the same way our linting is

I didn't get, why aren't you able to merge a PR that adds type info to all files?

**Comment by msaroufim** [comment]
We review all files before making updates. It's easy for those large sweeping PRs to introduce subtle bugs.

**Comment by sadra-barikbin** [comment]
> I've been wanting to add types for a a while. Would you like to setup typing for a single file? Also I won't be able to merge a PR that adds types for all files so the workflow needs to be progressive the same way our linting is

@msaroufim May I do this or you did it?

**Comment by msaroufim** [comment]
I'm working on it here https://github.com/pytorch/serve/pull/1858

**Pull request merged**
