### PR TITLE
[WIP] Added gpu support for windows native

### PR DESCRIPTION
**Pull request by dhaniram-kshirsagar**
## Description

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by maaquib** [comment]
@dhaniram-kshirsagar Please attach the sanity test and regression test logs

**Comment by jeremiahschung** [comment]
Confirming successful sanity test run on Windows 2019 with GPU. (CUDA 10.2, g4dn.xl)
[1209_pr851_gpu_win_success.txt](https://github.com/pytorch/serve/files/5669575/1209_pr851_gpu_win_success.txt)

Note that the install dependencies script still installs the torch binary for CUDA 10.1: 

Command: `python .\ts_scripts\install_dependencies.py --environment=dev --cuda=latest`
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.6.0
  Downloading https://download.pytorch.org/whl/cu101/torch-1.6.0%2Bcu101-cp38-cp38-win_amd64.whl (1021.6 MB)
```
```
(base) PS C:\serve> python -m torch.util.collect_env
C:\ProgramData\Anaconda3\python.exe: Error while finding module specification for 'torch.util.collect_env' (ModuleNotFoundError: No module named 'torch.util')
(base) PS C:\serve> python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows Server 2019 Datacenter
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 441.22
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] numpydoc==1.1.0
[pip3] torch==1.6.0+cu101
[pip3] torch-model-archiver==0.2.0b20201209
[pip3] torchaudio==0.6.0
[pip3] torchserve==0.2.0b20201209
[pip3] torchtext==0.7.0
[pip3] torchvision==0.7.0+cu101
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38hb782905_0
[conda] mkl_fft                   1.2.0            py38h45dec08_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.6.0+cu101              pypi_0    pypi
[conda] torch-model-archiver      0.2.0b20201209           pypi_0    pypi
[conda] torchaudio                0.6.0                    pypi_0    pypi
[conda] torchserve                0.2.0b20201209           pypi_0    pypi
[conda] torchtext                 0.7.0                    pypi_0    pypi
[conda] torchvision               0.7.0+cu101              pypi_0    pypi
(base) PS C:\serve>
```

**Comment by dhaniram-kshirsagar** [comment]
> **Note that the install dependencies script still installs the torch binary for CUDA 10.1:**
> 
> Command: `python .\ts_scripts\install_dependencies.py --environment=dev --cuda=latest`
> 
> ```
> Looking in links: https://download.pytorch.org/whl/torch_stable.html
> Collecting torch==1.6.0
>   Downloading https://download.pytorch.org/whl/cu101/torch-1.6.0%2Bcu101-cp38-cp38-win_amd64.whl (1021.6 MB)
> ```

@jeremiahschung Looks like there is some issue with pip install pytorch==1.6.0 i.e. it is always installed for cuda 10.1 instead of cuda 10.2. One of the reasons listed [here](https://discuss.pytorch.org/t/pytorch-for-cuda-10-2/65524) in pytorch forum is - pytorch comes with its own set of cuda libs and doesn't depend on local cuda installation.  Also, this [link](https://pytorch.org/get-started/previous-versions/#linux-and-windows-1) on pytorch.org for installing 1.6.0 for cuda 10.2 seems not working. If you still want to have it for cuda 10.2 then the as suggested solution in pytorch forum is to build pytorch from source using local cuda which can be a tricky business.

**Comment by jeremiahschung** [comment]
> > **Note that the install dependencies script still installs the torch binary for CUDA 10.1:**
> > Command: `python .\ts_scripts\install_dependencies.py --environment=dev --cuda=latest`
> > ```
> > Looking in links: https://download.pytorch.org/whl/torch_stable.html
> > Collecting torch==1.6.0
> >   Downloading https://download.pytorch.org/whl/cu101/torch-1.6.0%2Bcu101-cp38-cp38-win_amd64.whl (1021.6 MB)
> > ```
> 
> @jeremiahschung Looks like there is some issue with pip install pytorch==1.6.0 i.e. it is always installed for cuda 10.1 instead of cuda 10.2. One of the reasons listed [here](https://discuss.pytorch.org/t/pytorch-for-cuda-10-2/65524) in pytorch forum is - pytorch comes with its own set of cuda libs and doesn't depend on local cuda installation. Also, this [link](https://pytorch.org/get-started/previous-versions/#linux-and-windows-1) on pytorch.org for installing 1.6.0 for cuda 10.2 seems not working. If you still want to have it for cuda 10.2 then the as suggested solution in pytorch forum is to build pytorch from source using local cuda which can be a tricky business.

@dhaniram-kshirsagar Thanks for the response. Since this is out of scope of this PR, let's track this in a separate issue: https://github.com/pytorch/serve/issues/859

**Comment by jeffxtang** [comment]
On my Windows 10 Pro, I had CUDA 11.0 and PyTorch 1.7.1+ (it was 1.7.0 but was upgraded to 1.7.1 when I ran `python .\ts_scripts\install_dependencies.py --environment=dev`, with == changed to >= in the requirements\torch.txt) 

```
(base) PS C:\Users\Warrior\github> & 'C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe'
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 452.57       Driver Version: 452.57       CUDA Version: 11.0     |
===================+======================|
|   0  Quadro GP100       WDDM  | 00000000:01:00.0 Off |                  Off |
| 26%   31C    P0    25W / 235W |     89MiB / 16384MiB |      0%      Default |

pip list |grep torch
torch1.7.1+cu110

# inside ipython
In [6]: torch.cuda.get_device_name(0)
Out[6]: 'Quadro GP100'
```

The first time I ran `python .\torchserve_sanity.py`, 151 tests completed, 20 failed - result [win_gpu_torch171_sanity_test.txt](https://github.com/pytorch/serve/files/5676381/win_gpu_torch171_sanity_test.txt)

In the [TorchServe on Windows Troubleshooting](https://github.com/pytorch/serve/blob/master/docs/torchserve_on_win_native.md), it says "you may have to change the port number for inference, management and metrics apis as specified in frontend/server/src/test/resources/config.properties, all files in frontend/server/src/test/resources/snapshot/* and frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java, but it's unclear exactly how to make the changes. So I discarded the requirements/torch.txt changes, and installed torch 1.6.0 etc and reran the sanity test. The result is in [win_gpu_torch160_sanity_test.txt](https://github.com/pytorch/serve/files/5676380/win_gpu_torch160_sanity_test.txt), with the same number of failed tests, which may be caused by the same error `OSError: [WinError 10013] An attempt was made to access a socket` reported in issue #828.

**Comment by maaquib** [comment]
@jeffxtang Created #866 for the resolution of your issue

**Review by maaquib — APPROVED** [review]

**Review by dhanainme — APPROVED** [review]

**Pull request merged**
