### PR TITLE
[DO NOT MERGE] Benchmark cpu performance with IPEX launcher

### PR DESCRIPTION
**Pull request by min-jean-cho**
Compare nightly benchmark cpu performance with IPEX launcher enabled, expecting to see perf speedup from setting worker thread affinity.

### CODE REVIEW

**Comment by min-jean-cho** [comment]
Hi @lxning @msaroufim, could we try running the nightly benchmark on aws instance to compare the perf with ipex launcher enabled?

**Comment by msaroufim** [comment]
@agunapal do you have some instructions to run the benchmark suite locally

Otherwise was really hoping we could have some way of triggering them in CI by having for example a keyword in the description or a specific tag but that kept breaking the upload job @lxning

**Comment by min-jean-cho** [comment]
I'm mostly interested in seeing the performance speedup on cloud instances (e.g., aws) that customers would use. Because my local machine cpu config is probably different from cloud instances that customers would use (e.g., most cloud instances tend to be non-NUMA, etc).

**Comment by agunapal** [comment]
@msaroufim I suggested to change the benchmark github action to on push. Looks like she has done that, but I dont see the run triggering. Running locally is not helpful as @min-jean-cho wanted to mimic a realistic machine. Also, this would take really long to run on CPU.

**Comment by min-jean-cho** [comment]
By the way, is there a way to cancel workflow? I forgot to remove `export omp_num_threads=1`

**Comment by msaroufim** [comment]
@min-jean-cho just gave you write access, you should be able to cancel your own workflows now or retrigger them

**Comment by msaroufim** [comment]
This is a benchmark only PR so gonna close

**Pull request closed without merging**
