### PR TITLE
Updating index.md to fix 8 broken links

### PR DESCRIPTION
**Pull request by sekyondaMeta**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Fixed a couple of broken links in the index.md file. Fix affected about 5 files and is a result of how syphinx handles .md files to html by dropping the .md.
Added anchor links to each link .

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

Built pages locally on my machine and tested the different links. Attached is a screenshot of two of the links working from the index.html file.

Screenshot 2023-05-10 at 4 30 36 PM

## Checklist:

- [x] Did you have fun?
- [x] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
It's a small thing but helpful: when we make updates to certain pages I run a spellcheck on them so they're not typos you introduced but should be fixed nonetheless https://github.com/pytorch/serve/actions/runs/4941584585/jobs/8834328240?pr=2329 so if something is a typo you can fix and if it's not a typo you can add it here https://github.com/pytorch/serve/blob/master/ts_scripts/spellcheck_conf/wordlist.txt

**Comment by sekyondaMeta** [comment]
> It's a small thing but helpful: when we make updates to certain pages I run a spellcheck on them so they're not typos you introduced but should be fixed nonetheless https://github.com/pytorch/serve/actions/runs/4941584585/jobs/8834328240?pr=2329 so if something is a typo you can fix and if it's not a typo you can add it here https://github.com/pytorch/serve/blob/master/ts_scripts/spellcheck_conf/wordlist.txt

Makes sense. Will update the necessary files

**Comment by msaroufim** [comment]
LGTM, we usually need 2 stamps on the team so almost done!

**Comment by sekyondaMeta** [comment]
> LGTM, we usually need 2 stamps on the team so almost done!

Thanks for all the help

**Review by lxning — APPROVED** [review]

**Pull request merged**
