### PR TITLE
Implement Test for ModelRequestEncoder

### PR DESCRIPTION
**Pull request by abergmeier**
## Description

Implemented `ModelRequestEncoderTest`. Currently tests Inference protocol only.

## Type of change

Increased Unittest coverage for inference.

## Feature/Issue validation/testing

- [x] org.pytorch.serve.util.codec.ModelRequestEncoderTest.testEmpty
- [x] org.pytorch.serve.util.codec.ModelRequestEncoderTest.testSimple

## Checklist:

- [ ] Did you have fun?
- [x] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by mreso** [comment]
Hi @abergmeier thanks for contributing this test! Could you please address the CI failure?

**Comment by abergmeier** [comment]
> Hi @abergmeier thanks for contributing this test! Could you please address the CI failure?

Well the CI seems to have quite a bit of noise to signal ratio.
From what I could make out it seems like there is some formatting problem.
The CI and docs seem to be not very specific what formatting is expected/how that formatting can be reached.
Also, other CI failures seem to stem from flakiness.

So I am not really confident, that I will be able to solve CI failures without some guidance.

**Comment by agunapal** [comment]
@abergmeier Did you try building frontend https://github.com/pytorch/serve/tree/master/frontend

There is a formatter here https://github.com/pytorch/serve/blob/master/frontend/build.gradle#L45

**Comment by abergmeier** [comment]
> @abergmeier Did you try building frontend https://github.com/pytorch/serve/tree/master/frontend

frontend on `master` does not even build/test successful on my Ubuntu 22.04. I assume there is implicit configuration/dependencies which are not present on my machine.

> There is a formatter here https://github.com/pytorch/serve/blob/master/frontend/build.gradle#L45

Mabye I was not clear enough. I am no Java developer.
So for me to be able to produce a patch that is formatted in a way that you accept I assume I need a way of running a formatter on these files. I have no idea how I run the appropriate formatter.

**Comment by lxning** [comment]
@abergmeier you can format java code via command:

```
cd frontend
./gradlew format
```

**Comment by abergmeier** [comment]
Can this PR land?

**Review by mreso — APPROVED** [review]
LGTM

**Comment by mreso** [comment]
Thanks @abergmeier a lot for contributing this test

**Pull request merged**
