### PR TITLE
Fix set model state if runtime is null

### PR DESCRIPTION
**Pull request by mreso**
## Description
This PR fixes an issue when a model has no runtime set in the snapshot and we load with a newer torchserve version which expects the field.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- 
## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

## Checklist:

- [X] Did you have fun?
- [X] Have you added tests that prove your fix is effective or that this feature works?
- [X] Has code been commented, particularly in hard-to-understand areas?

### CODE REVIEW

**Review by agunapal — COMMENTED** [review]
How do we make sure that someone running 0.9.0 TS with snapshot upgrading to the latest will not run into an issue.
Can we test this manually and add logs here?

**Comment by mreso** [comment]
@ankithagunapal the new test test_empty_runtime covers that scenario by removing the runtime entry from the snapshot, but sure lets do this once manually.

**Comment by mreso** [comment]
> How do we make sure that someone running 0.9.0 TS with snapshot upgrading to the latest will not run into an issue. Can we test this manually and add logs here?

Here is the log of the test:
https://gist.github.com/mreso/f3ba1b41489e8bb76856b295ecacfadf

**Review by agunapal — APPROVED** [review]
LGTM

**Pull request merged**
