### PR TITLE
Change Config File for Windows

### PR DESCRIPTION
**Pull request by MengMeng96**
## Description

The config `management_address=unix:/tmp/management.sock` is not suitable for Windows. Change the config to `management_address=https://127.0.0.1:8444`. And as a result, the `expectedProp` in SnapshotTest() need to be modified.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by chauhang** [comment]
@maaquib Can you please comment on where `management_address=unix:/tmp/management.sock` is being used? Can we removed that to make things general instead of trying to add a separate windows version of config file

**Comment by MengMeng96** [comment]
> @maaquib Can you please comment on where `management_address=unix:/tmp/management.sock` is being used? Can we removed that to make things general instead of trying to add a separate windows version of config file

I tried to use a general config file but the build filed. When I use `management_address=https://127.0.0.1:8444`, the error logs are 
https://xf972w73p8.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=45fedfb2-2ab9-43e5-b2ae-15c5a4479e2d%2Fbuild.log
https://7p6qemywxh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=532287d4-67fa-4432-ac93-f2e65e88a64a%2Fbuild.log.
 When I use `management_address=https://127.0.0.1:8443`(the same as inference_address), the error logs are https://xf972w73p8.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=047e1351-da01-4f8d-bc12-11a148f49011%2Fbuild.log
https://7p6qemywxh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c91ff992-78a3-460d-82a2-6c42882569b2%2Fbuild.log.

As for the place where the `management_address` is used, as far as I know, ModelServer.start(), ConfigManager.dumpConfigurations(), ConfigManager.getListener(), etc. And all http requests uses the address.

**Comment by harshbafna** [comment]
> > @maaquib Can you please comment on where `management_address=unix:/tmp/management.sock` is being used? Can we removed that to make things general instead of trying to add a separate windows version of config file
> 
> @chauhang I tried to use a general config file but the build filed. When I use `management_address=https://127.0.0.1:8444`, the error logs are
> https://xf972w73p8.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=45fedfb2-2ab9-43e5-b2ae-15c5a4479e2d%2Fbuild.log
> https://7p6qemywxh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=532287d4-67fa-4432-ac93-f2e65e88a64a%2Fbuild.log.
> When I use `management_address=https://127.0.0.1:8443`(the same as inference_address), the error logs are https://xf972w73p8.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=047e1351-da01-4f8d-bc12-11a148f49011%2Fbuild.log
> https://7p6qemywxh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c91ff992-78a3-460d-82a2-6c42882569b2%2Fbuild.log.
> 
> As for the place where the `management_address` is used, as far as I know, ModelServer.start(), ConfigManager.dumpConfigurations(), ConfigManager.getListener(), etc. And all http requests uses the address.

@MengMeng96  : AFAIK, the management address in the existing `config.properties` file is only added to ensure that Unix-socket based addresses are supported. Changing it to use a proper port should not cause failures in the build.

Also, the codebuild logs shared above looks incomplete as the frontend UT suite isn't completed.

**Comment by harshbafna** [comment]
@MengMeng96: Could you please have a look at #612, which is also on similar lines as this PR, and check it satisfies your requirements?

**Pull request closed without merging**
